### ISSUE TITLE
"Unknown child" error message on startup

### ISSUE THREAD

**Issue by nomisbeme** [bitnami/bitnami-docker-php-fpm#10]
This container image emits a message on startup:

<snip> ALERT: oops, unknown child (5) exited with code 0. Please open a bug report (https://bugs.php.net).

This looks like a serious error message but it's purely informational and definitely doesn't warrant a bug report to the PHP guys. Is there any way to suppress this message or work-around the fact that it appears?

**Comment by prydonius** [comment]
Unfortunately this is a side effect of the asynchronous version check finishing after PHP-FPM becomes PID 1. Since PHP-FPM doesn't know about this process, it outputs this warning.

One way of avoiding the message would be to make the version check synchronous, so that it always finishes before PHP-FPM becomes PID 1. This will increase the start-up time, though.

Another option would be to use something like runit to manage processes so PHP-FPM doesn't have to run as PID 1, although it seems like overkill to use a process manager just to run PHP-FPM under it.

**Comment by sameersbn** [comment]
Issue was fixed in #14
