### ISSUE TITLE
Ability to run image read only

### ISSUE THREAD

**Issue by koehn** [bitnami/bitnami-docker-php-fpm#73]
I get an inexplicable error when I try to run the image with `--read-only`:

```
docker run --rm --read-only --tmpfs /tmp --tmpfs /root/.nami bitnami/php-fpm
```

It exits with error code 1, but I don't know what's wrong.

**Comment by sameersbn** [comment]
@koehn During the container launch, the container performs initialisation commands that modify files in `/root/.nami` and `/opt/bitnami/`. This behaviour causes issues if user tries to launch the container in readonly mode. Unfortunately you will not be able to use the `--readonly` flag.

**Comment by koehn** [comment]
Thanks for the response. 

Any chance you'd be willing to put that stuff in `/tmp`, and/or softlink it to its original locations?

**Comment by rquadling** [comment]
@stale It is not stale if the author's haven't responded.

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
